// Code generated by counterfeiter. DO NOT EDIT.
package helpersfakes

import (
	"sync"

	"github.com/petewall/eink-radiator/v2/internal/helpers"
)

type FakeSessionFactory struct {
	Stub        func(string, ...string) helpers.Session
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 string
		arg2 []string
	}
	returns struct {
		result1 helpers.Session
	}
	returnsOnCall map[int]struct {
		result1 helpers.Session
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSessionFactory) Spy(arg1 string, arg2 ...string) helpers.Session {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 string
		arg2 []string
	}{arg1, arg2})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("SessionFactory", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return returns.result1
}

func (fake *FakeSessionFactory) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeSessionFactory) Calls(stub func(string, ...string) helpers.Session) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeSessionFactory) ArgsForCall(i int) (string, []string) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2
}

func (fake *FakeSessionFactory) Returns(result1 helpers.Session) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 helpers.Session
	}{result1}
}

func (fake *FakeSessionFactory) ReturnsOnCall(i int, result1 helpers.Session) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 helpers.Session
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 helpers.Session
	}{result1}
}

func (fake *FakeSessionFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSessionFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ helpers.SessionFactory = new(FakeSessionFactory).Spy
