resources:
- name: eink-radiator
  type: git
  icon: github
  source:
    uri: git@github.com:petewall/eink-radiator
    branch: rearchitecture
    private_key: ((github.private_key))
- name: image-source-blank
  type: git
  icon: github
  source:
    uri: git@github.com:petewall/eink-radiator-image-source-blank
    branch: main
    private_key: ((github.private_key))
- name: image-source-image
  type: git
  icon: github
  source:
    uri: git@github.com:petewall/eink-radiator-image-source-image
    branch: main
    private_key: ((github.private_key))
- name: display
  type: git
  icon: github
  source:
    uri: git@github.com:petewall/eink-radiator-display
    branch: main
    private_key: ((github.private_key))
- name: eink-radiator-release
  type: github-release
  icon: github
  source:
    owner: petewall
    repository: eink-radiator
    access_token: ((github.access_token))
- name: image-source-blank-release
  type: github-release
  icon: github
  source:
    owner: petewall
    repository: eink-radiator-image-source-blank
    access_token: ((github.access_token))
- name: image-source-image-release
  type: github-release
  icon: github
  source:
    owner: petewall
    repository: eink-radiator-image-source-image
    access_token: ((github.access_token))
- name: display-release
  type: github-release
  icon: github
  source:
    owner: petewall
    repository: eink-radiator-display
    access_token: ((github.access_token))
- name: eink-radiator-version
  type: semver
  icon: github
  source:
    driver: git
    commit_message: '[ci skip] bump version to %version%'
    uri: git@github.com:petewall/eink-radiator.git
    branch: rearchitecture
    file: version
    private_key: ((github.private_key))
- name: image-source-blank-version
  type: semver
  icon: github
  source:
    driver: git
    commit_message: '[ci skip] bump version to %version%'
    uri: git@github.com:petewall/eink-radiator-image-source-blank.git
    branch: main
    file: version
    private_key: ((github.private_key))
- name: image-source-image-version
  type: semver
  icon: github
  source:
    driver: git
    commit_message: '[ci skip] bump version to %version%'
    uri: git@github.com:petewall/eink-radiator-image-source-image.git
    branch: main
    file: version
    private_key: ((github.private_key))
- name: display-version
  type: semver
  icon: github
  source:
    driver: git
    commit_message: '[ci skip] bump version to %version%'
    uri: git@github.com:petewall/eink-radiator-display.git
    branch: main
    file: version
    private_key: ((github.private_key))
- name: python
  type: registry-image
  icon: language-python
  source:
    repository: python
    tag: 3.9
- name: golang
  type: registry-image
  icon: language-go
  source:
    repository: golang
    tag: 1.19
jobs:
- name: test-eink-radiator
  plan:
  - in_parallel:
    - get: source
      resource: eink-radiator
      trigger: true
    - get: golang
  - task: lint
    image: golang
    config:
      platform: linux
      inputs:
      - name: source
      run:
        dir: source
        path: make
        args:
        - lint
  - task: test
    image: golang
    config:
      platform: linux
      inputs:
      - name: source
      run:
        dir: source
        path: make
        args:
        - test
- name: test-image-source-blank
  plan:
  - in_parallel:
    - get: source
      resource: image-source-blank
      trigger: true
    - get: golang
  - task: lint
    image: golang
    config:
      platform: linux
      inputs:
      - name: source
      run:
        dir: source
        path: make
        args:
        - lint
  - task: test
    image: golang
    config:
      platform: linux
      inputs:
      - name: source
      run:
        dir: source
        path: make
        args:
        - test
- name: test-image-source-image
  plan:
  - in_parallel:
    - get: source
      resource: image-source-image
      trigger: true
    - get: golang
  - task: lint
    image: golang
    config:
      platform: linux
      inputs:
      - name: source
      run:
        dir: source
        path: make
        args:
        - lint
  - task: test
    image: golang
    config:
      platform: linux
      inputs:
      - name: source
      run:
        dir: source
        path: make
        args:
        - test
- name: test-display
  plan:
  - in_parallel:
    - get: source
      resource: display
      trigger: true
    - get: python
  - task: lint
    image: python
    config:
      platform: linux
      inputs:
      - name: source
      run:
        dir: source
        path: make
        args:
        - lint
  - task: test
    image: python
    config:
      platform: linux
      inputs:
      - name: source
      run:
        dir: source
        path: make
        args:
        - test
- name: release-eink-radiator
  plan:
  - in_parallel:
    - get: source
      resource: eink-radiator
      passed:
      - test-eink-radiator
      trigger: true
    - get: golang
      passed:
      - test-eink-radiator
  - task: build
    image: golang
    config:
      platform: linux
      inputs:
      - name: source
      outputs:
      - name: build
      run:
        dir: source
        path: bash
        args:
        - -exc
        - |
          make build-all
          mv build/* ../build/
  - put: version
    resource: eink-radiator-version
    inputs: detect
    params:
      bump: patch
  - put: eink-radiator-release
    inputs:
    - build
    - source
    - version
    params:
      name: version/version
      tag: version/version
      tag_prefix: v
      commitish: source/.git/ref
      generate_release_notes: true
      globs:
      - build/*
- name: release-image-source-blank
  plan:
  - in_parallel:
    - get: source
      resource: image-source-blank
      passed:
      - test-image-source-blank
      trigger: true
    - get: golang
      passed:
      - test-image-source-blank
  - task: build
    image: golang
    config:
      platform: linux
      inputs:
      - name: source
      outputs:
      - name: build
      run:
        dir: source
        path: bash
        args:
        - -exc
        - |
          make build-all
          mv build/* ../build/
  - put: version
    resource: image-source-blank-version
    inputs: detect
    params:
      bump: patch
  - put: image-source-blank-release
    inputs:
    - build
    - source
    - version
    params:
      name: version/version
      tag: version/version
      tag_prefix: v
      commitish: source/.git/ref
      generate_release_notes: true
      globs:
      - build/*
- name: release-image-source-image
  plan:
  - in_parallel:
    - get: source
      resource: image-source-image
      passed:
      - test-image-source-image
      trigger: true
    - get: golang
      passed:
      - test-image-source-image
  - task: build
    image: golang
    config:
      platform: linux
      inputs:
      - name: source
      outputs:
      - name: build
      run:
        dir: source
        path: bash
        args:
        - -exc
        - |
          make build-all
          mv build/* ../build/
  - put: version
    resource: image-source-image-version
    inputs: detect
    params:
      bump: patch
  - put: image-source-image-release
    inputs:
    - build
    - source
    - version
    params:
      name: version/version
      tag: version/version
      tag_prefix: v
      commitish: source/.git/ref
      generate_release_notes: true
      globs:
      - build/*
- name: release-display
  plan:
  - in_parallel:
    - get: source
      resource: display
      passed:
      - test-display
      trigger: true
    - get: python
      passed:
      - test-display
  - task: build
    image: python
    config:
      platform: linux
      inputs:
      - name: source
      outputs:
      - name: build
      run:
        dir: source
        path: bash
        args:
        - -exc
        - |
          make build-all
          mv build/* ../build/
  - put: version
    resource: display-version
    inputs: detect
    params:
      bump: patch
  - put: display-release
    inputs:
    - build
    - source
    - version
    params:
      name: version/version
      tag: version/version
      tag_prefix: v
      commitish: source/.git/ref
      generate_release_notes: true
      globs:
      - build/*
