resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: source
    type: git
    icon: github
    source:
      uri: git@github.com:petewall/eink-radiator.git
      branch: master
      ignore_paths:
        - ci/*
        - ci/**
      private_key: ((github-repo-key))

  - name: pull-requests
    type: pull-request
    icon: github
    source:
      repository: petewall/eink-radiator
      access_token: ((github-access-token))

  - name: python
    type: registry-image
    icon: language-python
    source:
      repository: python
      tag: 3.7
      username: ((dockerhub-username))
      password: ((dockerhub-password))

  - name: node-js
    type: registry-image
    icon: nodejs
    source:
      repository: node
      tag: 14
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: test
    plan:
      - in_parallel:
        - get: python
        - get: node-js
        - get: source
          trigger: true
      - task: lint-python
        image: python
        config:
          platform: linux
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: [lint-python]
      - task: test-python
        image: python
        config:
          platform: linux
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: [test-units]
      - task: lint-javascript
        image: node-js
        config:
          platform: linux
          inputs:
            - name: source
          run:
            dir: source
            path: make
            args: [lint-js]

  - name: test-pull-request
    plan:
      - in_parallel:
        - get: python
        - get: node-js
        - get: source
          resource: pull-requests
          trigger: true
          version: every
          params:
            integration_tool: rebase
      - put: pull-requests
        params:
          path: source
          status: pending
      - do:
      - in_parallel:
        - task: lint-python
          image: python
          config:
            platform: linux
            inputs:
              - name: source
            run:
              dir: source
              path: make
              args: [lint-python]
          on_failure:
            put: pull-requests
            params:
              path: source
              status: failure
        - task: test-python
          image: python
          config:
            platform: linux
            inputs:
              - name: source
            run:
              dir: source
              path: make
              args: [test-units]
          on_failure:
            put: pull-requests
            params:
              path: source
              status: failure
        - task: lint-javascript
          image: node-js
          config:
            platform: linux
            inputs:
              - name: source
            run:
              dir: source
              path: make
              args: [lint-js]
          on_failure:
            put: pull-requests
            params:
              path: source
              status: failure
      - put: pull-requests
        params:
          path: source
          status: success
