resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: source
    type: git
    icon: github
    source:
      uri: git@github.com:petewall/eink-radiator.git
      branch: master
      ignore_paths:
        - ci/*
        - ci/**
      private_key: ((github-repo-key))

  - name: pull-requests
    type: pull-request
    source:
      repository: petewall/eink-radiator
      access_token: ((github-access-token))

jobs:
  - name: test
    plan:
      - get: source
        trigger: true
      - in_parallel:
        - task: lint-python
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: python
                tag: 3.7
                username: ((dockerhub-username))
                password: ((dockerhub-password))
            inputs:
              - name: source
            run:
              dir: source
              path: make
              args: [lint-python]
        - task: test-python
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: python
                tag: 3.7
                username: ((dockerhub-username))
                password: ((dockerhub-password))
            inputs:
              - name: source
            run:
              dir: source
              path: make
              args: [test-units]
        - task: lint-javascript
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: node
                tag: 14
                username: ((dockerhub-username))
                password: ((dockerhub-password))
            inputs:
              - name: source
            run:
              dir: source
              path: make
              args: [lint-js]

  - name: test-pull-request
    plan:
      - get: source
        resource: pull-requests
        trigger: true
        version: every
        params:
          integration_tool: rebase
      - put: pull-requests
        params:
          path: source
          status: pending
      - do:
      - in_parallel:
        - task: lint-python
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: python
                tag: 3.7
                username: ((dockerhub-username))
                password: ((dockerhub-password))
            inputs:
              - name: source
            run:
              dir: source
              path: make
              args: [lint-python]
          on_failure:
            put: pull-requests
            params:
              path: source
              status: failure
        - task: test-python
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: python
                tag: 3.7
                username: ((dockerhub-username))
                password: ((dockerhub-password))
            inputs:
              - name: source
            run:
              dir: source
              path: make
              args: [test-units]
          on_failure:
            put: pull-requests
            params:
              path: source
              status: failure
        - task: lint-javascript
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: node
                tag: 14
                username: ((dockerhub-username))
                password: ((dockerhub-password))
            inputs:
              - name: source
            run:
              dir: source
              path: make
              args: [lint-js]
          on_failure:
            put: pull-requests
            params:
              path: source
              status: failure
      - put: pull-requests
        params:
          path: source
          status: success
